type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  profilePictureUrl: String
  bio: String
}

type Anime @table {
  title: String!
  studio: String!
  releaseYear: Int!
  episodes: Int!
  description: String
  genres: [String]
  imageUrl: String
}

type Manga @table {
  title: String!
  author: String!
  publisher: String!
  publicationYear: Int!
  chapters: Int!
  description: String
  genres: [String]
  imageUrl: String
}

type UserAnime @table {
  user: User!
  anime: Anime!
  status: String!
  currentEpisode: Int!
  createdAt: Timestamp!
  rating: Int
  reviewText: String
}

type UserManga @table {
  user: User!
  manga: Manga!
  status: String!
  currentChapter: Int!
  createdAt: Timestamp!
  rating: Int
  reviewText: String
}

type Comment @table {
  user: User!
  userAnimeReview: UserAnime
  userMangaReview: UserManga
  content: String!
  createdAt: Timestamp!
  parentCommentId: UUID
}